### ISSUE TITLE
服务器错误

### ISSUE THREAD

**Issue by minewelt** [hongweipeng/MenuTree#5]
导入后激活的时候显示服务器错误是为什么

**Comment by hongweipeng** [comment]
能提供下报错信息之类的吗

**Comment by Tairitsua** [comment]
我也遇到了这个问题，贴个报错信息
无法启用插件
Typecho_Widget_Exception: 无法启用插件 in C:\phpStudy\PHPTutorial\WWW\blog\var\Widget\Plugins\Edit.php:98
Stack trace:
#0 C:\phpStudy\PHPTutorial\WWW\blog\var\Widget\Plugins\Edit.php(308): Widget_Plugins_Edit->activate('MenuTree-master')
#1 C:\phpStudy\PHPTutorial\WWW\blog\var\Widget\Do.php(82): Widget_Plugins_Edit->action()
#2 C:\phpStudy\PHPTutorial\WWW\blog\var\Typecho\Widget.php(221): Widget_Do->execute()
#3 C:\phpStudy\PHPTutorial\WWW\blog\var\Typecho\Router.php(135): Typecho_Widget::widget('Widget_Do', NULL, Array)
#4 C:\phpStudy\PHPTutorial\WWW\blog\index.php(23): Typecho_Router::dispatch()
#5 {main}

**Comment by Tairitsua** [comment]
发现将插件目录名从MenuTree-master改为MenuTree就好了，可能是-引起的原因
